"""Adding code column to ticket

Revision ID: 1c316c50f8bd
Revises: ab0483b74b98
Create Date: 2022-10-22 01:22:59.016385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c316c50f8bd'
down_revision = 'ab0483b74b98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'code')
    # ### end Alembic commands ###
