"""Adding price to destination

Revision ID: 34ca3cc9a91d
Revises: bcc492e9e901
Create Date: 2022-10-18 20:59:48.640880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34ca3cc9a91d'
down_revision = 'bcc492e9e901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depart', sa.Column('vehicule_fk', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'depart', 'vehicule', ['vehicule_fk'], ['id'])
    op.drop_column('depart', 'prix_place')
    op.add_column('destination', sa.Column('prix', sa.Numeric(), nullable=True))
    op.drop_column('ticket', 'bus_fk')
    op.drop_column('ticket', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticket', sa.Column('bus_fk', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('destination', 'prix')
    op.add_column('depart', sa.Column('prix_place', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'depart', type_='foreignkey')
    op.drop_column('depart', 'vehicule_fk')
    # ### end Alembic commands ###
