"""Last revision

Revision ID: 4f6dd936904e
Revises: 
Create Date: 2022-11-01 16:06:43.744960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f6dd936904e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colis',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_retrait', sa.DateTime(timezone=True), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('poids', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('prix', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destination',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prix', sa.Integer(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('mot_de_passe', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('etat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicule',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('plaque', sa.String(), nullable=True),
    sa.Column('nbre_place', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaque')
    )
    op.create_table('depart',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_heure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_fk', postgresql.UUID(), nullable=True),
    sa.Column('vehicule_fk', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['destination_fk'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['vehicule_fk'], ['vehicule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('passager', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('utilisateur_fk', postgresql.UUID(), nullable=True),
    sa.Column('depart_fk', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['depart_fk'], ['depart.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_fk'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('depart')
    op.drop_table('vehicule')
    op.drop_table('utilisateur')
    op.drop_table('destination')
    op.drop_table('colis')
    # ### end Alembic commands ###
