"""Adding token column to user table

Revision ID: 76a77bbca21c
Revises: 1c316c50f8bd
Create Date: 2022-11-01 23:51:45.623207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a77bbca21c'
down_revision = '1c316c50f8bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'token')
    # ### end Alembic commands ###
