"""Adding default value to devise

Revision ID: ab0483b74b98
Revises: 24aaaf9a928e
Create Date: 2022-10-18 22:11:27.718083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0483b74b98'
down_revision = '24aaaf9a928e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
