"""Moving prix_place to depart table

Revision ID: bcc492e9e901
Revises: 45c1f0ae7a1a
Create Date: 2022-10-12 01:25:04.543815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcc492e9e901'
down_revision = '45c1f0ae7a1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_column('bus', 'prix_place')
    op.add_column('depart', sa.Column('prix_place', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('depart', 'prix_place')
    op.add_column('bus', sa.Column('prix_place', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_table('config',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='config_pkey'),
    sa.UniqueConstraint('name', name='config_name_key')
    )
    # ### end Alembic commands ###
